export const SWITCHUNIT = "SALES_PRODUCT_CHART/SWITCHUNIT";
export const SWITCHTAB = "SALES_PRODUCT_CHART/SWITCHTAB";
export const FETCHCHARTDATA = "SALES_PRODUCT_CHART/FETCHCHARTDATA";

export const LASTMONTH = "SALES_PRODUCT_CHART/LASTMONTH";
export const NEXTMONTH = "SALES_PRODUCT_CHART/NEXTMONTH";
export const LASTYEAR = "SALES_PRODUCT_CHART/LASTYEAR";
export const NEXTYEAR = "SALES_PRODUCT_CHART/NEXTYEAR";
