export const SWITCHUNIT = "SALES_PRODUCT_CATEGORY/SWITCHUNIT";
export const SWITCHTAB = "SALES_PRODUCT_CATEGORY/SWITCHTAB";
export const FETCHCHARTDATA = "SALES_PRODUCT_CATEGORY/FETCHCHARTDATA";

export const LASTMONTH = "SALES_PRODUCT_CATEGORY/LASTMONTH";
export const NEXTMONTH = "SALES_PRODUCT_CATEGORY/NEXTMONTH";
export const LASTYEAR = "SALES_PRODUCT_CATEGORY/LASTYEAR";
export const NEXTYEAR = "SALES_PRODUCT_CATEGORY/NEXTYEAR";

