export const SWITCHUNIT = "SALES_CUSTOMER_CHART/SWITCHUNIT";
export const SWITCHTAB = "SALES_CUSTOMER_CHART/SWITCHTAB";
export const FETCHCHARTDATA = "SALES_CUSTOMER_CHART/FETCHCHARTDATA";

export const LASTMONTH = "SALES_CUSTOMER_CHART/LASTMONTH";
export const NEXTMONTH = "SALES_CUSTOMER_CHART/NEXTMONTH";
export const LASTYEAR = "SALES_CUSTOMER_CHART/LASTYEAR";
export const NEXTYEAR = "SALES_CUSTOMER_CHART/NEXTYEAR";
