export const SWITCHUNIT = "SALES_ORDER_CHART/SWITCHUNIT";
export const SWITCHTAB = "SALES_ORDER_CHART/SWITCHTAB";
export const FETCHCHARTDATA = "SALES_ORDER_CHART/FETCHCHARTDATA";

export const LASTMONTH = "SALES_ORDER_CHART/LASTMONTH";
export const NEXTMONTH = "SALES_ORDER_CHART/NEXTMONTH";
export const LASTYEAR = "SALES_ORDER_CHART/LASTYEAR";
export const NEXTYEAR = "SALES_ORDER_CHART/NEXTYEAR";




